Use IPADDR6_INIT() macro to set connecting IPv6 address
esphome/AsyncTCP pull request #14
Opened 2024-09-02 12:15 UTC by dwmw2

If LwIP is built with LWIP_IPV6_SCOPES, there is a 'zone' member in struct ip6_addr which was not being initialized correctly, leading to routing failures.

The tcp_connect() call would return ERR_RTE and we would completely fail to report that error. All the user would see is 'Connecting to MQTT...' over and over again.

2024-09-02 13:35 UTC, mathieucarbou commented
@dwmw2 : I took the liberty to get your fix in:
- https://github.com/mathieucarbou/AsyncTCP
- https://github.com/mathieucarbou/ESPAsyncWebServer

2024-09-04 04:50 UTC, HeMan reviewed
Would the macro `ip_addr_copy_from_ip6` give the same result? Otherwise, go with this.

2024-09-04 06:43 UTC, dwmw2 commented
> Would the macro `ip_addr_copy_from_ip6` give the same result? Otherwise, go with this.

No, I don't think there's a simpler option.

All this converting between `in_addr_t` and various Arduino and ESPHome C++ classes is kind of awful :)

2024-09-04 06:49 UTC, HeMan commented
> > Would the macro `ip_addr_copy_from_ip6` give the same result? Otherwise, go with this.
> 
> No, I don't think there's a simpler option.
> 
> All this converting between `in_addr_t` and various Arduino and ESPHome C++ classes is kind of awful :)

Yeah, I was hoping that the helper class in ESPHome would fix it all...

2024-09-04 06:49 UTC, HeMan approved these changes

2024-09-04 07:03 UTC, dwmw2 commented
> > > Would the macro `ip_addr_copy_from_ip6` give the same result? Otherwise, go with this.
> > 
> > 
> > No, I don't think there's a simpler option.
> > All this converting between `in_addr_t` and various Arduino and ESPHome C++ classes is kind of awful :)
> 
> Yeah, I was hoping that the helper class in ESPHome would fix it all...

Yeah, that's part of my sadness. Its constructor which takes an `arduino::IPAddress` assumes it will be Legacy IP and converts via `uint32_t`... I'll take a look at that later.

After we merge *this* PR can we have a 2.1.4 release please? I'll then require it from https://github.com/esphome/esphome/pull/7398

2024-09-05 08:03 UTC, HeMan commented
@jesserockz ready for merge!

2024-09-05 08:13 UTC, dwmw2 commented
And v2.1.4 tag please

2024-09-05 08:24 UTC, jesserockz requested changes

2024-09-05 08:24 UTC, jesserockz commented on library.json
> +  "version": "2.1.4",
Library version should not be bumped in PRs like this
```suggestion
  "version": "2.1.3",
```

2024-09-06 08:44 UTC, merged